name: Update Contributions

on:
  schedule:
    - cron: '0 0 * * 1' 
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install || echo "No dependencies"

      - name: Run contribution script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/analyzeContributions.js

      - name: Commit & push results
        run: |
          git config user.name "github-actions"
          git config user.email actions@github.com
          git add contributions.json
          git commit -m "Update contribution stats" || echo "No changes"
          git push
